name: Run tests and upload coverage

on:
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: 22

      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: Run tests and collect coverage
        run: make test && mvn jacoco:report

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        continue-on-error: true
        with:
          file: ./target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
